export const GRILLE_START = [
  [
    [5, null, 3, null, null, null, 8, null, 9],
    [null, 4, null, null, null, null, null, 3, null],
    [9, null, null, 6, 3, 8, null, null, 7],
    [null, null, 7, 4, null, 1, 5, null, null],
    [null, null, 4, null, 2, null, 7, null, null],
    [null, null, 5, 9, null, 3, 1, null, null],
    [8, null, null, 1, 9, 7, null, null, 4],
    [null, 1, null, null, null, null, null, 7, null],
    [4, null, 9, null, null, null, 2, null, 5],
  ],
  [
    [6, 4, null, 8, 3, 1, 5, 2, null],
    [null, null, 1, 6, 7, 2, 8, 9, null],
    [8, null, 7, 5, 4, null, 1, 6, null],
    [null, null, null, 1, 5, null, null, 8, null],
    [null, null, null, null, null, 6, null, null, null],
    [7, 5, null, null, null, null, null, null, 6],
    [null, 6, 2, 4, 1, null, null, null, null],
    [null, null, 4, 9, 2, null, null, null, null],
    [null, 8, 5, null, null, 3, null, 4, 9],
  ],
  [
    [null, null, null, 6, null, 1, null, null, null],
    [null, 8, 6, null, 3, null, 4, 1, null],
    [null, 2, null, null, null, null, null, 8, null],
    [2, null, null, 4, null, 8, null, null, 9],
    [null, 9, null, null, null, null, null, 4, null],
    [3, null, null, 1, null, 6, null, null, 2],
    [null, 5, null, null, null, null, null, 3, null],
    [null, 6, 9, null, 7, null, 1, 2, null],
    [null, null, null, 5, null, 9, null, null, null],
  ],
];
